/** @jest-environment node */
// ============================================================================
// Native/source parity for the SRD public flags.
//
// assets/content.db is generated by scripts/generate-content-db.mjs from the
// FULL spell/item libraries. On device the native repos (spellRepo.native /
// itemRepo.native) read it and, in an SRD-only build, drop every row whose
// `srd` column is not 1. These tests prove the shipped artifact and the
// source agree, and that the real native repos — driven by the real database
// file in EXPO_PUBLIC_SRD_ONLY=true mode — expose the same public set as the
// source bundle filters, while explicit-id loading of hidden ids still works
// (saved characters that reference them keep resolving).
// ============================================================================
const { DatabaseSync } = require('node:sqlite') as { DatabaseSync: new (path: string, options?: object) => any };
import path from 'node:path';
import { FULL_SPELL_LIBRARY } from '../spells/index';
import { FULL_ITEM_LIBRARY } from '../items/index';
import { CONTENT_DB_VERSION } from '../contentDbVersion';

const db = new DatabaseSync(path.resolve(process.cwd(), 'assets/content.db'), { readOnly: true });
const flag = (srd: boolean | undefined) => (srd === undefined ? null : srd ? 1 : 0);

const spellRows = db.prepare('SELECT id, name, srd FROM spells').all() as { id: string; name: string; srd: number | null }[];
const itemRows = db.prepare('SELECT id, name, srd FROM items').all() as { id: string; name: string; srd: number | null }[];

describe('content.db is in sync with source', () => {
  it('its contentVersion meta matches the generated CONTENT_DB_VERSION (i.e. it was regenerated)', () => {
    const row = db.prepare("SELECT value FROM meta WHERE key = 'contentVersion'").get() as { value: string };
    expect(row.value).toBe(CONTENT_DB_VERSION);
  });

  it('holds every source spell and item, none dropped (public exposure is not deletion)', () => {
    expect(spellRows).toHaveLength(FULL_SPELL_LIBRARY.length);
    expect(itemRows).toHaveLength(FULL_ITEM_LIBRARY.length);
    expect(new Set(spellRows.map(r => r.id))).toEqual(new Set(FULL_SPELL_LIBRARY.map(s => s.id)));
    expect(new Set(itemRows.map(r => r.id))).toEqual(new Set(FULL_ITEM_LIBRARY.map(i => i.id)));
  });

  it('spell srd flags and display names equal the source', () => {
    const byId = new Map(spellRows.map(r => [r.id, r]));
    const mismatches = FULL_SPELL_LIBRARY.filter(s => {
      const r = byId.get(s.id)!;
      return r.srd !== flag(s.srd) || r.name !== s.name;
    }).map(s => s.id);
    expect(mismatches).toEqual([]);
  });

  it('item srd flags and display names equal the source', () => {
    const byId = new Map(itemRows.map(r => [r.id, r]));
    const mismatches = FULL_ITEM_LIBRARY.filter(i => {
      const r = byId.get(i.id)!;
      return r.srd !== flag(i.srd) || r.name !== i.name;
    }).map(i => i.id);
    expect(mismatches).toEqual([]);
  });

  it('carries the corrected public metadata (spot checks)', () => {
    const spell = (id: string) => spellRows.find(r => r.id === id)!;
    const item = (id: string) => itemRows.find(r => r.id === id)!;
    expect(spell('hex').srd).toBe(0);
    expect(spell('telepathy').srd).toBe(0);
    expect(spell('evards_black_tentacles').srd).toBe(0);
    expect(spell('bigbys_hand')).toMatchObject({ name: 'Arcane Hand', srd: 1 });
    expect(spell('illusory_script').srd).toBe(1);
    expect(item('weapon_of_warning').srd).toBe(0);
    expect(item('defender_club').srd).toBe(0);
    expect(item('wondrous_figurine_onyx_dog').srd).toBe(1);
    expect(item('plate_mail')).toMatchObject({ name: 'Plate', srd: 1 });
    expect(item('healer_s_kit').srd).toBe(0);
  });
});

describe('native repos in SRD-only mode (real content.db)', () => {
  type Row = Record<string, unknown>;
  const adapter = {
    getAllAsync: async (sql: string, params: unknown[] = []) => db.prepare(sql).all(...params) as Row[],
  };

  function loadNative() {
    const previous = process.env.EXPO_PUBLIC_SRD_ONLY;
    process.env.EXPO_PUBLIC_SRD_ONLY = 'true';
    let mods!: {
      spellRepo: typeof import('../spellRepo.native').spellRepo;
      itemRepo: typeof import('../itemRepo.native').itemRepo;
      spells: typeof import('../spells/index');
      items: typeof import('../items/index');
    };
    try {
      jest.isolateModules(() => {
        jest.doMock('../../db/contentDb', () => ({ getContentDb: () => adapter }));
        mods = {
          spellRepo: require('../spellRepo.native').spellRepo,
          itemRepo: require('../itemRepo.native').itemRepo,
          spells: require('../spells/index'),
          items: require('../items/index'),
        };
      });
    } finally {
      if (previous === undefined) delete process.env.EXPO_PUBLIC_SRD_ONLY;
      else process.env.EXPO_PUBLIC_SRD_ONLY = previous;
    }
    return mods;
  }

  it('the native spell index equals the source public spell set', async () => {
    const { spellRepo, spells } = loadNative();
    await spellRepo.init();
    const nativeIds = spellRepo.getIndex().map(e => e.id).sort();
    const sourceIds = spells.ALL_SPELLS.map(s => s.id).sort();
    expect(nativeIds).toEqual(sourceIds);
    expect(nativeIds).toHaveLength(319);
    expect(spellRepo.getIndex().find(e => e.id === 'bigbys_hand')?.name).toBe('Arcane Hand');
  });

  it('the native item index equals the source public item set', async () => {
    const { itemRepo, items } = loadNative();
    await itemRepo.init();
    const nativeIds = itemRepo.getIndex().map(e => e.id).sort();
    const sourceIds = items.ALL_ITEMS.map(i => i.id).sort();
    expect(nativeIds).toEqual(sourceIds);
    expect(nativeIds).toHaveLength(95);
  });

  it('blocked private item ids cannot be explicitly loaded into SRD-only runtime', async () => {
    const { spellRepo, itemRepo } = loadNative();
    await spellRepo.init();
    await itemRepo.init();
    expect(spellRepo.getIndex().some(e => e.id === 'hex')).toBe(false);
    expect(itemRepo.getIndex().some(e => e.id === 'defender_club')).toBe(false);
    await spellRepo.ensureLoaded(['hex', 'evards_black_tentacles']);
    await itemRepo.ensureLoaded(['defender_club', 'healer_s_kit']);
    expect(spellRepo.getSpellSync('hex')?.name).toBe('Hex');
    expect(spellRepo.getSpellSync('evards_black_tentacles')?.id).toBe('evards_black_tentacles');
    expect(itemRepo.getItemSync('defender_club')).toBeUndefined();
    expect(itemRepo.getItemSync('healer_s_kit')).toBeUndefined();
  });
});

