/** Generated by scripts/generate-srd-public-items.ts; do not hand-edit. */
import generated from './generatedSrdItems.json';
import type { Item } from '../../engine/types';

export type GeneratedSrdProvenance = {
  public: true;
  verified: true;
  sourceType: 'structured-only';
  canonicalId: string;
  sourcePage: number;
  sourceEndPage: number;
  sourceHash: string;
  generatorVersion: number;
  publicRecordHash: string;
  fields: Record<string, string>;
};

export const GENERATED_SRD_ITEMS = generated.items as Item[];
export const GENERATED_SRD_ITEM_PROVENANCE = generated.provenance as Record<string, GeneratedSrdProvenance>;
