import { useMemo, useState } from 'react';
import { ScrollView, View, Text, TextInput, Pressable, StyleSheet } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { RULESETS, gameIdForRuleset, gameLabel, rulesetLabel } from '../../src/content/rulesets';
import { asRulesetId, AbilityGenerationMode, CampaignRules } from '../../src/engine/types';
import { makeCustomRuleProfile } from '../../src/engine/customRuleProfiles';
import { STANDARD_POINT_BUY } from '../../src/engine/pointBuy';
import { useCustomRuleProfileStore } from '../../src/store/customRuleProfileStore';
import { useCharacterStore } from '../../src/store/characterStore';
import { Alert } from '../../src/utils/alert';
import { HOUSE_RULES } from '../../src/engine/houseRules';
import { Colors, Spacing, Radius, FontSize, FontWeight } from '../../src/theme';

const MODES:{id:AbilityGenerationMode;label:string}[]=[{id:'standard',label:'Standard Array'},{id:'pointbuy',label:'Point Buy'},{id:'roll',label:'Roll 4d6'},{id:'manual',label:'Manual'}];
export default function RuleProfileScreen(){
 const {editId}=useLocalSearchParams<{editId?:string}>(),router=useRouter();
 const profiles=useCustomRuleProfileStore(s=>s.profiles),save=useCustomRuleProfileStore(s=>s.save),remove=useCustomRuleProfileStore(s=>s.remove);
 const existing=profiles.find(p=>p.id===editId),dndRulesets=useMemo(()=>Object.values(RULESETS).filter(r=>gameIdForRuleset(r.id)?.toString()==='dnd'),[]);
 const initial=existing?.rules??{};
 const [name,setName]=useState(existing?.name??''),[base,setBase]=useState(existing?.baseRulesetId??asRulesetId('dnd5e-2014'));
 const [hpMode,setHpMode]=useState<CampaignRules['hpMode']>(initial.hpMode??'fixed'),[multiclass,setMulticlass]=useState(initial.allowMulticlass??false),[useXP,setUseXP]=useState(initial.useXP??false);
 const [maxLevel,setMaxLevel]=useState(initial.maxLevel?.toString()??''),[maxAbility,setMaxAbility]=useState(initial.maxAbilityScore?.toString()??''),[customRules,setCustomRules]=useState<Record<string,unknown>>(initial.customRules??{});
 const [abilityMode,setAbilityMode]=useState<AbilityGenerationMode>(initial.abilityGenerationMode??'standard');
 const [pbBudget,setPbBudget]=useState(String(initial.pointBuy?.budget??STANDARD_POINT_BUY.budget)),[pbMin,setPbMin]=useState(String(initial.pointBuy?.minimum??STANDARD_POINT_BUY.minimum)),[pbMax,setPbMax]=useState(String(initial.pointBuy?.maximum??STANDARD_POINT_BUY.maximum));
 async function commit(){if(!name.trim())return;const rules:CustomRules={hpMode,allowMulticlass:multiclass,useXP,maxLevel:maxLevel.trim()?Number(maxLevel):null,maxAbilityScore:maxAbility.trim()?Number(maxAbility):null,customRules,abilityGenerationMode:abilityMode,...(abilityMode==='pointbuy'?{pointBuy:{budget:Number(pbBudget),minimum:Number(pbMin),maximum:Number(pbMax),costs:STANDARD_POINT_BUY.costs}}:{})};const now=Date.now();const profile=existing?{...existing,name:name.trim(),baseRulesetId:base,gameId:gameIdForRuleset(base)!,rules,updatedAt:now}:makeCustomRuleProfile({name,baseRulesetId:base,rules});await save(profile);router.back();}
 async function del(){if(!existing)return;const refs=new Set(useCharacterStore.getState().characters.map(c=>c.customRuleProfileId).filter((id):id is string=>!!id));const result=await remove(existing.id,refs);if(!result.ok)Alert.alert('Cannot delete profile',result.reason);else router.back();}
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
  <Text style={styles.title}>{existing?'Edit':'New'} Custom Rule Profile</Text>
  <Section title="PROFILE" help="A named set of overrides. Official rules remain unchanged."><Field label="Profile name" value={name} set={setName}/></Section>
  <Section title="BASED ON" help="This profile extends an official ruleset; it does not edit it."><Text style={styles.summary}>{name.trim()||'Custom profile'}
<Text style={styles.help}>Based on {rulesetLabel(base)} · {gameLabel(gameIdForRuleset(base))}</Text></Text>{dndRulesets.map(r=><Choice key={r.id} label={r.name} active={base===r.id} onPress={()=>setBase(r.id)}/>)}</Section>
  <Section title="CHARACTER EDITING" help="Controls whether players can use Free Edit."><Toggle label="Lock player Free Edit" value={customRules.lockPlayerFreeEdit===true} set={v=>setCustomRules(c=>({...c,lockPlayerFreeEdit:v}))}/></Section>
  <Section title="ABILITY GENERATION" help="The selected method opens automatically during character creation.">{MODES.map(m=><Choice key={m.id} label={m.label} active={abilityMode===m.id} onPress={()=>setAbilityMode(m.id)}/>)}{abilityMode==='pointbuy'&&<View style={styles.nested}><Field label="Budget" value={pbBudget} set={setPbBudget} numeric/><Field label="Minimum score" value={pbMin} set={setPbMin} numeric/><Field label="Maximum score" value={pbMax} set={setPbMax} numeric/><Text style={styles.help}>Uses the standard declarative 5e cost table: 8/0, 9/1, 10/2, 11/3, 12/4, 13/5, 14/7, 15/9.</Text></View>}</Section>
  <Section title="PROGRESSION & RECOVERY"><Choice label="Fixed HP" active={hpMode==='fixed'} onPress={()=>setHpMode('fixed')}/><Choice label="Rolled HP" active={hpMode==='rolled'} onPress={()=>setHpMode('rolled')}/><Choice label="Maximum HP" active={hpMode==='max'} onPress={()=>setHpMode('max')}/><Toggle label="Allow multiclassing" value={multiclass} set={setMulticlass}/><Toggle label="Use XP" value={useXP} set={setUseXP}/><Field label="Maximum level (blank = uncapped)" value={maxLevel} set={setMaxLevel} numeric/><Field label="Maximum ability score (blank = uncapped)" value={maxAbility} set={setMaxAbility} numeric/></Section>
  <Section title="OPTIONAL / HOUSE RULES" help="Only rule switches already supported by the engine are shown."><Toggle label="Allow feats" value={customRules.featsEnabled!==false} set={v=>setCustomRules(c=>({...c,featsEnabled:v}))}/>{HOUSE_RULES.filter(r=>r.key!=='lockPlayerFreeEdit'&&!['pointBuyPoints','pointBuyMin','pointBuyMax'].includes(r.key)).map(rule=>rule.kind==='boolean'?<Toggle key={rule.key} label={rule.label} value={customRules[rule.key]===true} set={v=>setCustomRules(c=>({...c,[rule.key]:v}))}/>:<View key={rule.key}><Text style={styles.fieldLabel}>{rule.label}</Text>{rule.options?.map(o=><Choice key={o.value} label={o.label} active={(customRules[rule.key]??rule.choiceDefault)===o.value} onPress={()=>setCustomRules(c=>({...c,[rule.key]:o.value}))}/>)}</View>)}</Section>
  <Pressable style={styles.save} onPress={()=>void commit()}><Text style={styles.saveText}>Save Profile</Text></Pressable>{existing&&<Pressable style={styles.delete} onPress={()=>void del()}><Text style={styles.deleteText}>Delete Profile</Text></Pressable>}
 </ScrollView>;
}
type CustomRules=Partial<CampaignRules>&{customRules?:Record<string,unknown>};
function Section({title,help,children}:{title:string;help?:string;children:React.ReactNode}){return <View style={styles.card}><Text style={styles.section}>{title}</Text>{help&&<Text style={styles.help}>{help}</Text>}{children}</View>}
function Field({label,value,set,numeric}:{label:string;value:string;set:(v:string)=>void;numeric?:boolean}){return <View><Text style={styles.fieldLabel}>{label}</Text><TextInput style={styles.input} value={value} onChangeText={set} keyboardType={numeric?'number-pad':'default'} placeholderTextColor={Colors.textDim}/></View>}
function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable style={[styles.row,active&&styles.active]} onPress={onPress}><Text style={styles.text}>{active?'✓ ':''}{label}</Text></Pressable>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <Choice label={label} active={value} onPress={()=>set(!value)}/>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:Colors.bg},content:{padding:Spacing.lg,paddingBottom:Spacing.xxl},title:{fontSize:FontSize.xl,fontWeight:FontWeight.bold,color:Colors.gold,marginBottom:Spacing.md},card:{backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.lg,padding:Spacing.md,marginBottom:Spacing.md},section:{fontSize:FontSize.md,fontWeight:FontWeight.black,color:Colors.gold,letterSpacing:1,marginBottom:Spacing.xs},help:{color:Colors.textDim,fontSize:FontSize.xs,marginBottom:Spacing.sm,lineHeight:17},summary:{color:Colors.textPrimary,fontSize:FontSize.lg,fontWeight:FontWeight.bold,marginBottom:Spacing.md},fieldLabel:{color:Colors.textSecondary,fontWeight:FontWeight.bold,marginTop:Spacing.sm,marginBottom:Spacing.xs},input:{backgroundColor:Colors.bg,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,padding:Spacing.md,color:Colors.textPrimary,marginBottom:Spacing.xs},row:{borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,padding:Spacing.sm,marginBottom:Spacing.xs,minHeight:44,justifyContent:'center'},active:{borderColor:Colors.gold,backgroundColor:Colors.gold+'18'},text:{color:Colors.textPrimary,fontSize:FontSize.sm},nested:{borderLeftWidth:2,borderLeftColor:Colors.gold,paddingLeft:Spacing.md,marginTop:Spacing.sm},save:{backgroundColor:Colors.gold,borderRadius:Radius.md,padding:Spacing.md,alignItems:'center'},saveText:{color:Colors.bg,fontWeight:FontWeight.bold},delete:{padding:Spacing.md,alignItems:'center'},deleteText:{color:Colors.red,fontWeight:FontWeight.bold}});
