import { makeEmptyEntity, DEFAULT_RULES } from '../../store/characterStore';
import { applyCharacterOverride, removeCharacterOverride } from '../characterOverride';
import { applyDmOverride, cancelDmOverride } from '../dmOverride';
import { effectiveAbilityScores } from '../pipeline';
import { explainValue } from '../audit';
import { adjustPointBuy, minimumPointBuyScores, STANDARD_POINT_BUY, validatePointBuy } from '../pointBuy';
import { makeCustomRuleProfile, resolveEffectiveCampaignRules } from '../customRuleProfiles';
import { asRulesetId } from '../types';

describe('device UI closure pass 4',()=>{
 it('layers character replacement before DM replacement and removes independently',()=>{let e=makeEmptyEntity('override');e.stats.str=10;e=applyCharacterOverride(e,{stat:'str',value:15},DEFAULT_RULES);expect(effectiveAbilityScores(e).str).toBe(15);const manualId=e.characterOverrides!.find(o=>o.active)!.id;e=applyDmOverride(e,{campaignId:'c',entityId:e.id,dmDeviceId:'dm',stat:'str',operation:'set',value:20,label:'Campaign ruling',expiry:'manual'},DEFAULT_RULES);expect(effectiveAbilityScores(e).str).toBe(20);const dmId=e.dmOverrides.find(o=>o.active)!.id;e=cancelDmOverride(e,dmId,DEFAULT_RULES);expect(effectiveAbilityScores(e).str).toBe(15);e=removeCharacterOverride(e,manualId,DEFAULT_RULES);expect(effectiveAbilityScores(e).str).toBe(10);});
 it('works standalone, persists through JSON, and explains replacements without additive math',()=>{let e=applyCharacterOverride(makeEmptyEntity('solo'),{stat:'ac',value:18},DEFAULT_RULES);e=JSON.parse(JSON.stringify(e));expect(e.derived.ac).toBe(18);const audit=explainValue(e,'ac');expect(audit.entries.at(-1)).toMatchObject({sourceKind:'character_override',replacement:{to:18},value:0});});
 it('final CON drives HP and removing DM falls back to character CON',()=>{let e=makeEmptyEntity('con');e.identity.level=2;e.stats.con=10;e.resources.hp={maximum:20,current:12,temp:0};e=applyCharacterOverride(e,{stat:'con',value:14},DEFAULT_RULES);expect(e.resources.hp).toMatchObject({maximum:24,current:16});e=applyDmOverride(e,{campaignId:'c',entityId:e.id,dmDeviceId:'d',stat:'con',operation:'set',value:18,label:'DM',expiry:'manual'},DEFAULT_RULES);expect(e.resources.hp.maximum).toBe(28);e=cancelDmOverride(e,e.dmOverrides.find(o=>o.active)!.id,DEFAULT_RULES);expect(effectiveAbilityScores(e).con).toBe(14);expect(e.resources.hp).toMatchObject({maximum:24,current:16});});
 it('calculates budget, increases, decreases/refunds, and enforces min/max/unaffordable moves',()=>{const min=minimumPointBuyScores(STANDARD_POINT_BUY);expect(validatePointBuy(min,STANDARD_POINT_BUY)).toMatchObject({valid:true,spent:0,remaining:27});const raised=adjustPointBuy(min,'str',1,STANDARD_POINT_BUY);expect(raised.str).toBe(9);expect(validatePointBuy(raised,STANDARD_POINT_BUY).remaining).toBe(26);expect(adjustPointBuy(raised,'str',-1,STANDARD_POINT_BUY)).toEqual(min);expect(adjustPointBuy(min,'str',-1,STANDARD_POINT_BUY)).toBe(min);const max={str:15,dex:15,con:15,int:8,wis:8,cha:8};expect(adjustPointBuy(max,'str',1,STANDARD_POINT_BUY)).toBe(max);expect(adjustPointBuy(max,'int',1,STANDARD_POINT_BUY)).toBe(max);});
 it('rejects invalid cost-table and overspent allocations',()=>{expect(validatePointBuy({str:16,dex:8,con:8,int:8,wis:8,cha:8},STANDARD_POINT_BUY).valid).toBe(false);expect(validatePointBuy({str:15,dex:15,con:15,int:15,wis:15,cha:15},STANDARD_POINT_BUY).valid).toBe(false);});
 it('profile selects Point Buy and carries a custom declarative budget through effective rules',()=>{const profile=makeCustomRuleProfile({id:'pb',name:'Point Buy',baseRulesetId:asRulesetId('dnd5e-2014'),rules:{abilityGenerationMode:'pointbuy',pointBuy:{...STANDARD_POINT_BUY,budget:30}}});const e={...makeEmptyEntity('draft'),rulesetId:profile.baseRulesetId,customRuleProfileId:profile.id};const rules=resolveEffectiveCampaignRules(DEFAULT_RULES,e,[profile]);expect(rules.abilityGenerationMode).toBe('pointbuy');expect(rules.pointBuy?.budget).toBe(30);const persisted=JSON.parse(JSON.stringify({...e,creationAbilityMode:'pointbuy',stats:minimumPointBuyScores(rules.pointBuy!)}));expect(persisted.creationAbilityMode).toBe('pointbuy');expect(validatePointBuy(persisted.stats,rules.pointBuy!).valid).toBe(true);});
});
