// ============================================================================
// FILE: src/content/bundledPacks.ts
// The first-party SRD packs that ship with the app as files (assets/packs/*.json, generated by
// scripts/build-srd-packs.ts), so the first-run chooser and the "install" buttons can offer them with one tap instead of
// asking the player to find a file. A bundled pack goes through exactly the same install path as one imported from a file
// (hash check, validation, dependencies, all or nothing). Each file is only read when a pack is actually installed.
// ============================================================================
import { installOfficialPack, installedOfficialPacks, PackStore, ServiceResult } from './officialPackService';

export type BundledPack = { id: string; name: string; summary: string; ruleset: string; load: () => unknown };

export const BUNDLED_PACKS: readonly BundledPack[] = [
  {
    id: 'grimoire.srd.5.1', name: 'SRD 5.1', ruleset: 'dnd5e-2014',
    summary: 'D&D 5e (2014) compatible: the System Reference Document 5.1 classes, species, spells, items and monsters.',
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    load: () => require('../../assets/packs/grimoire.srd.5.1.json'),
  },
  {
    id: 'grimoire.srd.5.2.1', name: 'SRD 5.2.1', ruleset: 'dnd5e-2024',
    summary: 'D&D 5.5e (2024) compatible: the System Reference Document 5.2.1 classes, species, backgrounds, Origin feats, spells and Weapon Mastery. Needs SRD 5.1.',
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    load: () => require('../../assets/packs/grimoire.srd.5.2.1.json'),
  },
];

/** The pack ids to install for a request, with what each depends on added first (SRD 5.2.1 brings SRD 5.1). */
export function withDependencies(ids: readonly string[]): string[] {
  const out: string[] = [];
  const visit = (id: string) => {
    if (out.includes(id)) return;
    const pack = BUNDLED_PACKS.find(p => p.id === id);
    if (!pack) return;
    const manifest = (pack.load() as { manifest?: { dependencies?: { id: string }[] } }).manifest;
    for (const dep of manifest?.dependencies ?? []) visit(dep.id);
    out.push(id);
  };
  ids.forEach(visit);
  return out;
}

/** Installs the chosen bundled packs (and what they need), skipping any already installed. Stops at the first problem. */
export async function installBundledPacks(ids: readonly string[], store: PackStore): Promise<ServiceResult> {
  for (const id of withDependencies(ids)) {
    if (installedOfficialPacks().some(p => p.manifest.id === id)) continue;
    const pack = BUNDLED_PACKS.find(p => p.id === id)!;
    const result = await installOfficialPack(pack.load(), store, { signed: 'require' });
    if (!result.ok) return { ok: false, problems: [`${pack.name} could not be installed:`, ...result.problems] };
  }
  return { ok: true };
}
