// src/io/exportHtml.ts
// HTML builders for homebrew PDF export — siblings to characterSheetPdf.ts,
// which stays untouched and character-specific. Reuses expo-print via
// exportShare.ts's sharePdfHtml rather than a second PDF mechanism. Simpler
// single-column shareable pages, not a print-optimized table sheet.
import { CharClass, ClassProgression, Feature, Grant, HomebrewSubclass, Spell } from '../engine/types';

function esc(s: string | null | undefined): string {
  if (!s) return '';
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

const PAGE_STYLE = `
  @page { size: letter; margin: 0.6in; }
  * { box-sizing: border-box; }
  body { font-family: 'Georgia', serif; color: #1a1a1a; font-size: 11px; }
  .title { font-size: 24px; font-weight: bold; border-bottom: 2px solid #1a1a1a; padding-bottom: 8px; margin-bottom: 12px; }
  .subtitle { font-size: 12px; color: #555; font-style: italic; margin-bottom: 12px; }
  .meta { font-size: 11px; color: #333; margin-bottom: 12px; }
  .meta b { color: #000; }
  .section-title { font-weight: bold; font-size: 15px; margin-top: 18px; margin-bottom: 6px; border-bottom: 1px solid #999; padding-bottom: 3px; }
  .feature { margin-bottom: 10px; line-height: 1.4; }
  .feature-name { font-weight: bold; font-style: italic; }
  .feature-meta { font-size: 9px; color: #888; }
  .dim { color: #888; }
  .footer-note { margin-top: 20px; font-size: 8px; color: #999; text-align: center; }
`;

function page(title: string, subtitle: string, body: string): string {
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>${PAGE_STYLE}</style></head>
<body>
  <div class="title">${esc(title)}</div>
  ${subtitle ? `<div class="subtitle">${esc(subtitle)}</div>` : ''}
  ${body}
  <div class="footer-note">Generated by Grimoire — for personal table use.</div>
</body></html>`;
}

function featureHtml(f: Feature): string {
  const cost = f.activation?.resourceCost
    ? ` · costs ${f.activation.resourceCost.quantity} ${esc(f.activation.resourceCost.resourceId)}`
    : '';
  return `<div class="feature">
    <div class="feature-name">${esc(f.name)}.</div>
    <div>${esc(f.description) || '<span class="dim">(no description)</span>'}</div>
    ${f.activation ? `<div class="feature-meta">${esc(f.activation.actionType)}${cost}</div>` : ''}
  </div>`;
}

/** A standalone homebrew Feature (the generic feature-editor builder's output). */
export function buildStandaloneFeatureHtml(f: Feature): string {
  const cost = f.activation?.resourceCost
    ? ` · costs ${f.activation.resourceCost.quantity} ${esc(f.activation.resourceCost.resourceId)}`
    : '';
  const body = `
    <div>${esc(f.description) || '<span class="dim">(no description)</span>'}</div>
    ${f.activation ? `<div class="feature-meta">${esc(f.activation.actionType)}${cost}</div>` : ''}
  `;
  return page(f.name, '', body);
}

/** Generic "name + flat Feature[]" renderer — Race, Subrace, Background, Item. */
export function buildFeatureListHtml(title: string, subtitle: string, features: Feature[]): string {
  const body = features.length
    ? features.map(featureHtml).join('')
    : '<div class="dim">No features.</div>';
  return page(title, subtitle, body);
}

/** Walks entries[].grants[], grouping embedded Feature grants under a per-level heading. */
export function buildProgressionHtml(title: string, progression: ClassProgression): string {
  const sorted = [...progression.entries].sort((a, b) => a.level - b.level);
  const body = sorted
    .map(entry => {
      const featureGrants = entry.grants.filter((g: Grant) => g.kind === 'feature');
      if (featureGrants.length === 0) return '';
      return `<div class="section-title">Level ${entry.level}</div>
        ${featureGrants.map(g => featureHtml(g.value as Feature)).join('')}`;
    })
    .join('');
  return page(title, '', body);
}

export function buildHomebrewSubclassHtml(sub: HomebrewSubclass): string {
  return buildProgressionHtml(sub.name, sub);
}

/** Same rawProgression-vs-simplified-fields split as exportText.ts's buildClassMarkdown. */
export function buildClassHtml(cls: CharClass): string {
  if (cls.rawProgression) return buildProgressionHtml(cls.name, cls.rawProgression);

  const byLevel = new Map<number, NonNullable<CharClass['levelFeatures']>>();
  for (const lf of cls.levelFeatures ?? []) {
    if (!byLevel.has(lf.level)) byLevel.set(lf.level, []);
    byLevel.get(lf.level)!.push(lf);
  }

  const level1 = `<div class="section-title">Level 1</div>
    ${cls.features.length ? cls.features.map(featureHtml).join('') : '<div class="dim">No level 1 features.</div>'}`;

  const restLevels = [...byLevel.keys()].sort((a, b) => a - b).map(level => `
    <div class="section-title">Level ${level}</div>
    ${byLevel.get(level)!.map(lf => `<div class="feature"><div class="feature-name">${esc(lf.name)}.</div><div>${esc(lf.description) || '<span class="dim">(no description)</span>'}</div></div>`).join('')}
  `).join('');

  return page(cls.name, `Hit Die: d${cls.hitDie}`, level1 + restLevels);
}

export function buildSpellHtml(spell: Spell): string {
  const levelLabel = spell.level === 0 ? 'Cantrip' : `Level ${spell.level}`;
  const body = `
    <div class="meta">
      <b>Casting Time:</b> ${esc(spell.castingTime)}<br/>
      <b>Range:</b> ${esc(spell.range)}<br/>
      <b>Components:</b> ${esc(spell.components.join(', '))}<br/>
      <b>Duration:</b> ${esc(spell.duration)}${spell.concentration ? ' (concentration)' : ''}
    </div>
    <div>${esc(spell.description)}</div>
    ${spell.upcast ? `<div style="margin-top:8px;"><b>At Higher Levels.</b> ${esc(spell.upcast)}</div>` : ''}
  `;
  return page(spell.name, `${levelLabel} ${esc(spell.school)}${spell.ritual ? ' (ritual)' : ''}`, body);
}
